#ifndef POL_POM_QT_PLUGINS_STEAM_GLOBAL_H
#define POL_POM_QT_PLUGINS_STEAM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POL_POM_QT_PLUGINS_STEAM_LIBRARY)
#  define POL_POM_QT_PLUGINS_STEAMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define POL_POM_QT_PLUGINS_STEAMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // POL_POM_QT_PLUGINS_STEAM_GLOBAL_H
