TEMPLATE = subdirs
SUBDIRS += $$PWD/POL_POM_QT/src/POL_POM_QT.pro \
           $$PWD/POL_POM_QT_LIB_COMMON/POL_POM_QT_LIB_COMMON.pro \
           $$PWD/POL_POM_QT_LIB_VIRTUALDRIVE/POL_POM_QT_LIB_VIRTUALDRIVE.pro \
           $$PWD/POL_POM_QT_PLUGINS_STEAM/src/POL_POM_QT_PLUGINS_STEAM.pro \
           $$PWD/POL_POM_QT_PLUGINS_VIRTUALDRIVEMANAGER/src/POL_POM_QT_PLUGINS_VIRTUALDRIVEMANAGER.pro

$PWD/POL_POM_QT/src/POL_POM_QT.pro.depends = $$PWD/POL_POM_QT_LIB_COMMON/POL_POM_QT_LIB_COMMON.pro
$PWD/POL_POM_QT/src/POL_POM_QT.pro.depends = $$PWD/POL_POM_QT_LIB_VIRTUALDRIVE/POL_POM_QT_LIB_VIRTUALDRIVE.pro

$$PWD/POL_POM_QT_LIB_VIRTUALDRIVE/POL_POM_QT_LIB_VIRTUALDRIVE.pro.depends = $$PWD/POL_POM_QT_LIB_COMMON/POL_POM_QT_LIB_COMMON.pro

$$PWD/POL_POM_QT_PLUGINS_VIRTUALDRIVEMANAGER/src/POL_POM_QT_PLUGINS_VIRTUALDRIVEMANAGER.pro.depends = $$PWD/POL_POM_QT_LIB_VIRTUALDRIVE/POL_POM_QT_LIB_VIRTUALDRIVE.pro

RESOURCES += \
    POL_POM_QT_PLUGINS_VIRTUALDRIVEMANAGER/src/resources/mainwindowres.qrc
